---
- name: Reload systemd daemon (networking)
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart network anchor
  ansible.builtin.systemd_service:
    name: mando-net-anchor.service
    state: restarted

- name: Restart dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq
    state: restarted

- name: Reload nftables
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded
