// Package session defines the one identifier that threads through the whole system.
//
// Per PLAN §5 the session_id is generated by Temporal at workflow start and used,
// unchanged, as the Temporal workflow ID, the NATS subject prefix, the workspace volume
// filename, the jailer chroot directory name, the git branch, the Slack thread key, and
// the correlation field on every log line. Do not introduce a second identifier.
//
// Format: "s_" followed by 26 Crockford base32 characters (ULID-style), matching
// ^s_[0-9A-HJKMNP-TV-Z]{26}$.
package session

import (
	"crypto/rand"
	"fmt"
	"regexp"
)

// Pattern is the canonical session_id format (PLAN §5).
var Pattern = regexp.MustCompile(`^s_[0-9A-HJKMNP-TV-Z]{26}$`)

// crockford is Crockford base32: digits plus A–Z excluding I, L, O, U.
const crockford = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

const suffixLen = 26

// ID is a validated session identifier. The zero value is invalid; construct via Parse
// or New. Because tap device names are capped at 15 characters, never derive short forms
// except through TapName, and never treat a truncated form as unique on its own (§5).
type ID string

// Parse validates s and returns it as an ID, or an error if it is malformed.
func Parse(s string) (ID, error) {
	if !Pattern.MatchString(s) {
		return "", fmt.Errorf("invalid session_id %q: must match %s", s, Pattern.String())
	}
	return ID(s), nil
}

// MustParse is Parse that panics on error. For tests and constant inputs only.
func MustParse(s string) ID {
	id, err := Parse(s)
	if err != nil {
		panic(err)
	}
	return id
}

// New generates a fresh valid ID. Temporal is the real source of session_ids in
// production (§5); New exists for tests, local tooling, and the reconciler's fixtures.
func New() (ID, error) {
	buf := make([]byte, suffixLen)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("session: read randomness: %w", err)
	}
	out := make([]byte, 0, suffixLen+2)
	out = append(out, 's', '_')
	for _, b := range buf {
		out = append(out, crockford[int(b)%len(crockford)])
	}
	return ID(out), nil
}

// String returns the identifier unchanged.
func (id ID) String() string { return string(id) }

// Valid reports whether id is well-formed.
func (id ID) Valid() bool { return Pattern.MatchString(string(id)) }

// Branch returns the git branch an agent pushes to for this session: agent/<session_id>.
func (id ID) Branch() string { return "agent/" + string(id) }

// WorkflowID returns the Temporal workflow ID, which is the session_id itself (§5).
func (id ID) WorkflowID() string { return string(id) }

// SubjectPrefix returns the NATS subject prefix "agent.<session_id>" (§5); callers append
// the leaf, e.g. SubjectPrefix()+".event".
func (id ID) SubjectPrefix() string { return "agent." + string(id) }

// tapMaxLen is the Linux network-interface name limit (IFNAMSIZ-1).
const tapMaxLen = 15

// TapName derives the host tap device name for this session. Interface names are capped
// at 15 characters, so this is a deliberate, documented truncation of the ULID suffix and
// is NOT unique on its own (§5) — fleet-agent tracks the authoritative session_id in the
// per-VM state directory. Form: "tap" + first 12 chars of the suffix.
func (id ID) TapName() string {
	suffix := string(id)[2:] // drop "s_"
	n := tapMaxLen - len("tap")
	if len(suffix) > n {
		suffix = suffix[:n]
	}
	return "tap" + suffix
}
